INSERT INTO COM_LIST_MASTER (ID, CATEGORY)
VALUES (1, "POI");

INSERT INTO COM_LIST_MASTER (ID, CATEGORY)
VALUES (2, "CITY");

INSERT INTO COM_LIST_MASTER (ID, CATEGORY)
VALUES (3, "AREA");

INSERT INTO COM_LIST_MASTER (ID, CATEGORY)
VALUES (4, "DURATION");